In [1]:
import numpy as np


In [2]:
a=np.array([12,13,23.78,45])
print(a) # if there is a single float value,every element of array datatype will be float type

[12.   13.   23.78 45.  ]


In [4]:
print("Array Type : ",type(a))

Array Type :  <class 'numpy.ndarray'>


In [6]:
print("Data Type : ",a.dtype)b


Data Type :  float64


In [7]:
#find dimenations
print("Dimensions :",a.ndim)

Dimensions : 1


In [9]:
#find shape of a array
print("Shape :",a.shape)

Shape : (4,)


In [10]:
# Create a 2D array
b = np.array([[12,13,23.78,45],[45,22,45,55]])
print(b)

[[12.   13.   23.78 45.  ]
 [45.   22.   45.   55.  ]]


In [13]:
print("Array type ",type(b))
print("Data type",b.dtype)
print("Dimensions: ",b.ndim)
print("Shape :",b.shape)

Array type  <class 'numpy.ndarray'>
Data type float64
Dimensions:  2
Shape : (2, 4)


In [14]:
# Create 3D Arrays
s = np.array([[[1,2,3],[10,20,30]],[[5,6,7],[8,9,10]]])
print(s)

[[[ 1  2  3]
  [10 20 30]]

 [[ 5  6  7]
  [ 8  9 10]]]


In [15]:

print("Array type ",type(s))
print("Data type",s.dtype)
print("Dimensions: ",s.ndim)
print("shape :",s.shape)

Array type  <class 'numpy.ndarray'>
Data type int32
Dimensions:  3
shape : (2, 2, 3)


In [17]:
# create a 2D 
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
array1 = np.arange(1,32,2).reshape(4,4)
array1

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31]])

In [19]:
print("Array type ",type(array1))
print("Data type",array1.dtype)
print("Dimensions: ",array1.ndim)
print("shape :",array1.shape)

Array type  <class 'numpy.ndarray'>
Data type int32
Dimensions:  2
shape : (4, 4)


In [20]:
print(array1[1:3]) # it will print row 1,2

[[ 9 11 13 15]
 [17 19 21 23]]


In [21]:
print(array1[1:3,2:4]) # it will print  1,2 row's of 2,3 columns 


[[13 15]
 [21 23]]


In [22]:
print(array1[1,-1]) # it will print last element of 1st row 

15


In [23]:
# update element 
array1[2,1] = 80

In [24]:
print(array1)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 80 21 23]
 [25 27 29 31]]


In [27]:
# create zero's array 
zero_array = np.zeros((3,3),dtype = 'int32')
print(zero_array)
print("Data type : ",zero_array.dtype)
ones_array = np.ones((3,3))
print(ones_array) # if we don't define data type of element , it will by defualt consider float
print("Data type : ",ones_array.dtype)
empty_array = np.empty((3,3))
print(empty_array)
print("Data type : ",empty_array.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Data type :  int32
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Data type :  float64
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Data type :  float64


In [29]:
empty_array = np.empty([3,3])
print(empty_array)
print("Data type : ",empty_array.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Data type :  float64


In [28]:
empty_array = np.empty(3,3)
print(empty_array)
print("Data type : ",empty_array.dtype)

#When creating an array filled with zeros using np.empty(), you need to pass the shape as a single argument,
#------which should be a tuple or list

TypeError: data type not understood

"""In NumPy, float64 refers to the data type for floating-point numbers with 64 bits of precision. It is also known as double precision.

The term "64" in float64 represents the number of bits used to store each floating-point value."""

In [30]:
new_array = ones_array+ empty_array
print(new_array)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [34]:
# update data type of array
# It's important to note that the astype() method returns a new array with the updated dtype, 
# ---rather than modifying the original array in-place.
new_array = new_array.astype(int)
print(new_array)
print("Data Type of New Array ",new_array.dtype)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
Data Type of New Array  int32


In [36]:
print(new_array*ones_array.astype(int)) # matrix multiplication

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [38]:
print(empty_array.dot(new_array))

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [40]:
"""
The dot product or matrix multiplication is performed by taking the sum of the elementwise multiplication of 
the corresponding rows in the first array (a) and the corresponding columns in the second array (b).
"""
a = np.array([[1, 2],[3, 4]])
print(a)
b = np.array([[5, 6],[7, 8]])
print(b)
print(a.dot(b))
#result[0, 0] = (1 * 5) + (2 * 7) = 19
#result[0, 1] = (1 * 6) + (2 * 8) = 22
#result[1, 0] = (3 * 5) + (4 * 7) = 43
#result[1, 1] = (3 * 6) + (4 * 8) = 50

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [42]:
# identity matrix / unix matrix 
# --- Diagonal elements ( top left to bottom) are 1 and other are 0 
# if will create only squre identity matrix
a = np.identity(3,dtype ='int')
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [45]:
# eye() is used to create an identity matrix or an array with ones along themain diagonal and zeros elsewhere
# It can create both square and non-square identity matrices.
#It takes three parameters: m (number of rows), n (number of columns, optional), and k (diagonal offset, optional)
b = np.eye(3,4,dtype='int32')
print(b)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [47]:
b = np.eye(3,4,k=1,dtype='int32')
print(b) # k determines diagonal offset, which means is filled with ones
#Setting k to a positive or negative integer moves the diagonal up or down, respectively.


[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# Filter Array 

In [50]:
arr = np.array([1,2,3,4,5])
condition = arr%2 ==0 # condition is boolean array of same shape 
#[False, True, False, True, False]
filter_array = arr[condition]
print(filter_array)
###you can apply the condition to the array using boolean indexing. Boolean indexing involves passing the condition inside 
# ---square brackets to select the elements that satisfy the condition.

[2 4]


In [51]:
a=np.array([[12,13,14,15],[3,24,13,6],[10,18,1,2]])
print(a)

[[12 13 14 15]
 [ 3 24 13  6]
 [10 18  1  2]]


In [52]:
print(a[a%6==0])

[12 24  6 18]


In [53]:
print(a[a>5])

[12 13 14 15 24 13  6 10 18]


# to search the values
# np.where() --- it returns the indices where the condition is True, allowing 
# --- allow you to filter or replace element in an array 


'''
The condition a % 2 == 0 is evaluated. This condition checks if each element in the array a is divisible by 2 without  
remainder.The result is a boolean array of the same shape as a, where each element is 
True if the corresponding element in a is even and False otherwise.

The np.where() function is then applied to this condition. It takes the boolean array as the argument and returns the indices 
where the condition is True. In this case, it returns a tuple containing the row indices of the even elements.

The expression np.where(a % 2 == 0)[0] retrieves the first element of the tuple returned by np.where(). This element 
contains the row indices where the condition is True.

The .data attribute is then accessed, which returns a pointer to the data of the array.
This is an implementation detail and is not typically used directly in regular code.
'''


In [ ]:
print(list(np.where(a%2==0)))

In [55]:
# to find sum of all values 

print(np.sum(a,axis =1)) # row wise sum
print(np.sum(a,axis =0))# column wise sum
print(np.sum(a))


[54 46 31]
[25 55 28 23]
131


In [56]:
#to find mean
print(np.mean(a))

10.916666666666666


In [59]:
#hstack and vstack
x=np.array([10,20,30])
y=np.array([11,12,13])
z=np.array([21,22,23])
d = np.vstack((x,y,z))
print(np.hstack((x,y,z)))
print(np.vstack((x,y,z)))

[10 20 30 11 12 13 21 22 23]
[[10 20 30]
 [11 12 13]
 [21 22 23]]


In [60]:
#revesrse columns and rows both

np.flip(d)

array([[23, 22, 21],
       [13, 12, 11],
       [30, 20, 10]])

In [61]:
np.flip(d,axis=1)
# If you want to reverse only the columns of an array while keeping the rows unchanged, you can specify axis=1

array([[30, 20, 10],
       [13, 12, 11],
       [23, 22, 21]])

In [62]:
#endpoint=False will exclude 30
x=np.linspace(10,30,7,endpoint=False) # 3rd params : generate number of values between start and stop values
print(x) # endpoint = False --means stop value 30 will not be included in the generated values

[10.         12.85714286 15.71428571 18.57142857 21.42857143 24.28571429
 27.14285714]


In [69]:
# creating an array with random values 
random_arr = np.random.randint(1,10,size = (3,3))# create a 3*3 array with random values
print(random_arr)
random_arr.dtype

[[4 2 5]
 [9 6 7]
 [7 4 2]]


dtype('int32')

In [68]:
random_float_arr = np.random.rand(3,3) # create a 3*3 array with random values
print(random_float_arr)

[[0.68689682 0.09569931 0.24391501]
 [0.66012544 0.95724244 0.43773735]
 [0.04072332 0.33562691 0.58639292]]


Broadcasting in NumPy allows arrays with different shapes to be used together in arithmetic operations. It automatically aligns the shapes of arrays to perform element-wise operations efficiently. Here are a few examples to illustrate broadcasting:

In [70]:
arr = np.array([1,2,3,4])
scalar = 5
result = arr + scalar
print(result)

[6 7 8 9]


In [71]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10], [20]])

result = arr1 + arr2
print(result)


[[11 12 13]
 [24 25 26]]


In [ ]:
# fancy Indexing 
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([1, 3])

#The element at index 1 in arr is 20, and the element at index 3 is 40. These elements are selected and returned in the resulting array.
result = arr[indices] # it will create a result array 
print(result)
